name: Build Aseprite for Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++ libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev libcurl4-openssl-dev libfreetype6-dev

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build Aseprite
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=../third_party/skia -DSKIA_LIBRARY_DIR=../third_party/skia/out/Release-x64 -DSKIA_LIBRARY=../third_party/skia/out/Release-x64/libskia.a ..
          make -j$(nproc)

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-linux
          path: build/bin/aseprite
